import img2hd from 'my-shared/function/img2/img2hd.js';
import down from 'my-shared/function/download/down.js';
import downimg from 'my-shared/function/download/downimg.js';
import view from 'my-shared/function/other/view.js';
import member from 'my-shared/function/group/member.js';
import polling from 'my-shared/function/group/polling.js';
import hidetag from 'my-shared/function/group/hidetsg.js';
import tagall from 'my-shared/function/group/tagall.js';
import listadmin from 'my-shared/function/group/listadmin.js';
import linkgc from 'my-shared/function/group/linkgc.js';
import time from 'my-shared/function/group/time.js';
import name_desc from 'my-shared/function/group/name_desc.js';
import pp from 'my-shared/function/group/pp.js';
import teks2img from 'my-shared/function/img2/text2img.js';
import teks2stiker from 'my-shared/function/teks2/teks2stiker.js';
import imgmaker from 'my-shared/function/ai/imgmaker.js';
import chatai from 'my-shared/function/ai/chatai.js';
import audiomake from 'my-shared/function/other/audiomaker.js';
import stikerms from 'my-shared/function/_ms/stiker_ms.js';
import cekms from 'my-shared/function/_ms/cek_ms.js';
import stikerpp from 'my-shared/function/other/stikerpp.js';
import img2stiker from 'my-shared/function/img2/img2stiker.js';
import vid2stiker from 'my-shared/function/other/vid2stiker.js';
import menuf from 'my-shared/function/menu.js';
import kisahnabi from 'my-shared/function/islamic/kisahnabi.js';
import asmaulhusna from 'my-shared/function/islamic/asmaulhusna.js';
import bacaansholat from 'my-shared/function/islamic/bacaansolat.js';
import doaharian from 'my-shared/function/islamic/doaharian.js';
import quotesislami from 'my-shared/function/islamic/quotesislami.js';
import niatsholat from 'my-shared/function/islamic/niatsholat.js';
import ayatkursi from 'my-shared/function/islamic/ayatkursi.js';
import alquran from 'my-shared/function/islamic/alquran.js';
import audiosurah from 'my-shared/function/islamic/audiosurah.js';
import jadwalsholat from 'my-shared/function/islamic/jadwalsholat.js';
import img_ms from 'my-shared/function/_ms/img_ms.js';
import vid_ms from 'my-shared/function/_ms/vid_ms.js';
import tp_ms from 'my-shared/function/pay/tp.js';
import puls_ms from 'my-shared/function/pay/puls.js';
import vcr_ms from 'my-shared/function/pay/vcr.js';
import carimsk from 'my-shared/function/music/carimsk.js';
import carilirik from 'my-shared/function/music/carilirik.js';
import carianime from 'my-shared/function/anime/carianime.js';
import chatanime from 'my-shared/function/anime/chatanime.js';
import infoanime from 'my-shared/function/anime/infoanime.js';
import game from 'my-shared/function/_ms/game_ms.js';
import list from 'my-shared/function/_ms/listms.js';
import admin from 'my-shared/function/admin.js';

const mainData = [
    { command: ".imgmaker", function: imgmaker },
    { command: ".audiomaker", function: audiomake },
    { command: ".teks2img", function: teks2img },
    { command: ".teks2stiker", function: teks2stiker },
    { command: ".chatai", function: chatai },
    { command: ".chatanime", function: list },
    { command: ".carianime", function: carianime },
    { command: ".cekkodam", function: cekms },
    { command: ".cekjodoh", function: cekms },
    { command: ".cekiq", function: cekms },
    { command: ".listgame", function: list },
    { command: ".liststiker", function: list },
    { command: ".listmember", function: member },
    { command: ".menu", function: menuf },

    { command: ".grup", function: list },
    { command: ".makepolling", function: polling },
    { command: ".view", function: view },
    { command: ".tagall", function: tagall },
    { command: ".hidetag", function: hidetag },
    { command: ".visibeltag", function: tagall },
    { command: ".member", function: member },
    { command: ".listadmin", function: listadmin },
    { command: ".linkgc", function: linkgc },
    { command: ".time", function: time },
    { command: ".ppgc", function: pp },
    { command: ".descgc", function: name_desc },
    { command: ".namegc", function: name_desc },

    { command: ".stiker", function: list },
    { command: ".stikeranim", function: stikerms },
    { command: ".stikerteks", function: stikerms },
    { command: ".stikerjmk", function: stikerms },
    { command: ".stikerwowo", function: stikerms },
    { command: ".stikerrandom", function: stikerms },
    { command: ".stikerpp", function: stikerpp },
    { command: ".img2stiker", function: img2stiker },
    { command: ".vid2stiker", function: vid2stiker },

    { command: ".admin", function: list },
    { command: ".mute", function: admin },
    { command: ".setwelcome", function: admin },
    { command: ".setleave", function: admin },
    { command: ".nolink", function: admin },
    { command: ".nolinkgc", function: admin },
    { command: ".nolinkch", function: admin },
    { command: ".nolinktiktok", function: admin },
    { command: ".nolinkfb", function: admin },
    { command: ".nolinktwitter", function: admin },
    { command: ".nolinkig", function: admin },
    { command: ".nolinktg", function: admin },
    { command: ".nolinkdc", function: admin },
    { command: ".nolinkytvid", function: admin },
    { command: ".nolinkytch", function: admin },
    { command: ".nolinksosmed", function: admin },
    { command: ".notoxic", function: admin },
    { command: ".nospam", function: admin },
    { command: ".setppgroup", function: admin },
    { command: ".delppgroup", function: admin },
    { command: ".setnamegroup", function: admin },
    { command: ".setdescgrpup", function: admin },
    { command: ".editinfo", function: admin },
    { command: ".add", function: admin },
    { command: ".kick", function: admin },
    { command: ".createadmin", function: admin },
    { command: ".cabutadmin", function: admin },

    { command: ".islami", function: list },
    { command: ".kisahnabi", function: kisahnabi },
    { command: ".asmaulhusna", function: asmaulhusna },
    { command: ".bacaansholat", function: bacaansholat },
    { command: ".audiosurah", function: audiosurah },
    { command: ".ayatkursi", function: ayatkursi },
    { command: ".doaharian", function: doaharian },
    { command: ".niatsholat", function: niatsholat },
    { command: ".quotesislami", function: quotesislami },
    { command: ".alquran", function: alquran },
    { command: ".jadwalsholat", function: jadwalsholat },

    { command: ".image", function: list },
    { command: ".imganim", function: img_ms },
    { command: ".imgteks", function: img_ms },
    { command: ".imgwowo", function: img_ms },
    { command: ".imgrandom", function: img_ms },
    { command: ".imgmeme", function: img_ms },
    { command: ".imgestetik", function: img_ms },
    { command: ".imgjmk", function: img_ms },
    { command: ".img2hd", function: img2hd },

    { command: ".vidio", function: list },
    { command: ".vidjj", function: vid_ms },
    { command: ".vidwowo", function: vid_ms },
    { command: ".vidrandom", function: vid_ms },
    { command: ".vidmeme", function: vid_ms },
    { command: ".videstetik", function: vid_ms },
    { command: ".vidjmk", function: vid_ms },

    { command: ".topup", function: list },
    { command: ".tpff", function: tp_ms },
    { command: ".tpml", function: tp_ms },
    { command: ".tppubg", function: tp_ms },
    { command: ".tprbx", function: tp_ms },
    { command: ".tpgshin", function: tp_ms },
    { command: ".tplol", function: tp_ms },
    { command: ".tphnkai", function: tp_ms },
    { command: ".tpvalo", function: tp_ms },
    { command: ".tphok", function: tp_ms },
    { command: ".tpzzz", function: tp_ms },
    { command: ".tpaov", function: tp_ms },
    { command: ".tpea", function: tp_ms },
    { command: ".tpafk", function: tp_ms },
    { command: ".tpvidio", function: tp_ms },
    { command: ".tpminecraft", function: tp_ms },
    { command: ".tpspsus", function: tp_ms },
    { command: ".tpcodm", function: tp_ms },
    { command: ".tpmladv", function: tp_ms },
    { command: ".tpmcgg", function: tp_ms },
    { command: ".tparenab", function: tp_ms },
    { command: ".tpblodstrk", function: tp_ms },
    { command: ".tpdeltaforc", function: tp_ms },
    { command: ".tpindus", function: tp_ms },
    { command: ".tpgarena", function: tp_ms },
    { command: ".tpgglvcr", function: tp_ms },
    { command: ".tpracingmstr", function: tp_ms },
    { command: ".tpundown", function: tp_ms },
    { command: ".tp8ball", function: tp_ms },
    { command: ".tpheavendmn", function: tp_ms },
    { command: ".tpdragonhtrs", function: tp_ms },
    { command: ".tpspeeddrft", function: tp_ms },
    { command: ".tpcrisisact", function: tp_ms },
    { command: ".tpzepeto", function: tp_ms },
    { command: ".tpfootbllmngr", function: tp_ms },
    { command: ".tpfrostwarr", function: tp_ms },
    { command: ".tpragnarogclsc", function: tp_ms },

    { command: ".pulsa", function: list },
    { command: ".data", function: list },
    { command: ".pulstri", function: puls_ms },
    { command: ".pulstelkom", function: puls_ms },
    { command: ".pulsindost", function: puls_ms },
    { command: ".pulsxl", function: puls_ms },
    { command: ".pulsim3", function: puls_ms },
    { command: ".pulsaxis", function: puls_ms },
    { command: ".pulssmartf", function: puls_ms },
    { command: ".pulsbyu", function: puls_ms },
    { command: ".dattri", function: puls_ms },
    { command: ".dattelkom", function: puls_ms },
    { command: ".datindost", function: puls_ms },
    { command: ".datxl", function: puls_ms },
    { command: ".datim3", function: puls_ms },
    { command: ".dataxis", function: puls_ms },
    { command: ".datsmartf", function: puls_ms },
    { command: ".datbyu", function: puls_ms },

    { command: ".vcr", function: list },
    { command: ".token", function: list },
    { command: ".tknpln", function: vcr_ms },
    { command: ".vcrvidio", function: vcr_ms },
    { command: ".vcrggply", function: vcr_ms },
    { command: ".vcrrbx", function: vcr_ms },
    { command: ".vcrvision", function: vcr_ms },
    { command: ".vcrtiktokkoin", function: vcr_ms },
    { command: ".vcrminecraft", function: vcr_ms },
    { command: ".vcrtwitch", function: vcr_ms },
    { command: ".vcrsteam", function: vcr_ms },
    { command: ".vcrnitendo", function: vcr_ms },
    { command: ".vcrgarenashll", function: vcr_ms },
    { command: ".vcrxbox", function: vcr_ms },

    { command: ".msk", function: list },
    { command: ".carimsk", function: carimsk },
    { command: ".carilirik", function: carilirik },

    { command: ".game", function: list },
    { command: ".sudoku", function: game },
    { command: ".ulartangga", function: game },
    { command: ".uno", function: game },
    { command: ".poker", function: game },
    { command: ".tord", function: game },
    { command: ".snack", function: game },
    { command: ".ludo", function: game },
    { command: ".pingpong", function: game },
    { command: ".tictactoe", function: game },
    { command: ".monopoli", function: game },
    { command: ".puzzle", function: game },
    { command: ".darts", function: game },
    { command: ".tennis", function: game },
    { command: ".pool", function: game },
    { command: ".mathgame", function: game },
    { command: ".popit", function: game },
    { command: ".rubix", function: game },
    { command: ".carrom", function: game },
    { command: ".hammerhit", function: game },
    { command: ".bowling", function: game },
    { command: ".checkers", function: game },
    { command: ".pinball", function: game },
    { command: ".minisoccer", function: game },
    { command: ".mancala", function: game },
    { command: ".dotsandboxes", function: game },
    { command: ".domino", function: game },
    { command: ".yesorno", function: game },
    { command: ".pizza", function: game },
    { command: ".glowit", function: game },
    { command: ".fiveo", function: game },
    { command: ".lazzergrrl", function: game },
    { command: ".islandroccer", function: game },
    { command: ".donutvsdonut", function: game },
    { command: ".tuggowar", function: game },
    { command: ".bowman", function: game },
    { command: ".minesweeper", function: game },
    { command: ".hexa", function: game },
    { command: ".unpuzzle", function: game },
    { command: ".pipeout", function: game },
    { command: ".rollup", function: game },
    { command: ".link", function: game },
    { command: ".beam", function: game },
    { command: ".emojipuzzle", function: game },
    { command: ".mahjong", function: game },
    { command: ".nutspuzzle", function: game },
    { command: ".masterofnumber", function: game },
    { command: ".yacht", function: game },
    { command: ".entropy", function: game },
    { command: ".get1000", function: game },
    { command: ".pixblock", function: game },
    { command: ".splotch", function: game },
    { command: ".orange", function: game },
    { command: ".black", function: game },
    { command: ".red", function: game },
    { command: ".nonogram", function: game },
    { command: ".xor", function: game },
    { command: ".sokoban", function: game },
    { command: ".redirect", function: game },
    { command: ".ruya", function: game },
    { command: ".baseball", function: game },
    { command: ".miniputt", function: game },
    { command: ".boxing", function: game },
    { command: ".volley", function: game },
    { command: ".punchers", function: game },
    { command: ".fourcolors", function: game },
    { command: ".kuja", function: game },
    { command: ".cubicrush", function: game },
    { command: ".dodgeball", function: game },
    { command: ".gengsters", function: game },
    { command: ".rollingballs", function: game },
    { command: ".whooo?", function: game },
    { command: ".bloxorz", function: game },
    { command: ".rotate", function: game },
    { command: ".glitch", function: game },
    { command: ".growmi", function: game },
    { command: ".green", function: game },
    { command: ".pollytrack", function: game },
    { command: ".rodha", function: game },
    { command: ".mirrorroom", function: game },
    { command: ".tilo", function: game },
    { command: ".monomove", function: game },
    { command: ".googlefeud", function: game },
    { command: ".jetrush", function: game },
    { command: ".countmasters", function: game },
    { command: ".wordguessr", function: game },
    { command: ".doodleroad", function: game },
    { command: ".marblerun", function: game },
    { command: ".driftboss", function: game },
    { command: ".replyrun", function: game },
    { command: ".openhouse", function: game },
    { command: ".layersrol", function: game },
    { command: ".smashkarts", function: game },
    { command: ".fragen", function: game },
    { command: ".sugarrush", function: game },
    { command: ".stickman", function: game },
    { command: ".skillwarz", function: game },
    { command: ".gulag", function: game },
    { command: ".takeactions", function: game },
    { command: ".furyfoot", function: game },
    { command: ".tunnel54", function: game },
    { command: ".gunsandmagic", function: game },

    { command: ".noa", function: chatanime },
    { command: ".shiroko", function: chatanime },
    { command: ".hoshino", function: chatanime },
    { command: ".yuuka", function: chatanime },
    { command: ".hikari", function: chatanime },
    { command: ".furina", function: chatanime },
    { command: ".hutao", function: chatanime },
    { command: ".klee", function: chatanime },
    { command: ".miko", function: chatanime },
    { command: ".lumine", function: chatanime },
    { command: ".raiden", function: chatanime },

    { command: ".anime", function: list },
    { command: ".carigenre", function: infoanime },
    { command: ".carifulleps", function: infoanime },
    { command: ".carifulltrailer", function: infoanime },
    { command: ".carifulldesc", function: infoanime },
    { command: ".carifulldurasi", function: infoanime },
    { command: ".caritgglrilis", function: infoanime },
    { command: ".caritotaleps", function: infoanime },
    { command: ".carikarakter", function: infoanime },
    { command: ".caribanner", function: infoanime },

    { command: ".viddownload", function: list },
    { command: ".downig", function: down },
    { command: ".downtiktok", function: down },
    { command: ".downfb", function: down },
    { command: ".downx", function: down },
    { command: ".downyt", function: down },
    { command: ".downcc", function: down },
    { command: ".downgdrive", function: down },
    { command: ".downpintrs", function: down },
    { command: ".downdouyin", function: down },
    { command: ".downdsnackvideo", function: down },
    { command: ".downdcocofun", function: down },
    { command: ".downdspotify", function: down },
    { command: ".downdsoundcloud", function: down },
    { command: ".downdthreads", function: down },

    { command: ".imgdownload", function: list },
    { command: ".imgtiktok", function: downimg },
    { command: ".imgpintrs", function: downimg },
    { command: ".imgig", function: downimg },
]

export default mainData;