export const downSosmed = [
    {command: ".downig" , varname: "igdl", contohUrl:'https://www.instagram.com/p/ByxKbUSnubS/?eig_web_copy_link', lokasi: "result[0].url"},
    {command: ".downtiktok" , varname: "aio", contohUrl:'https://vt.tiktok.com/ZSudELyTDsdsddssasa/', lokasi: "data.links.video[0].url"},
    {command: ".downfb" , varname: "fbdown", contohUrl:'https://www.facebook.com/watch/?v=1393572814172251/', lokasi:"Normal_video"},
    {command: ".downyt" , varname: "youtube", contohUrl:'https://youtube.com/watch?v=C8mJ8943X80', lokasi: "mp4"},
    {command: ".downcc" , varname: "capcut", contohUrl:'https://www.capcut.com/template-l/7221?template_id=66074.....', lokasi:"originalVideoUrl"},
    {command: ".downgdrive" , varname: "gdrive", contohUrl:'https://drive.google.com/file/d/1thDYWcS5p5FFhzTpTev7RU', lokasi:"result.data.downloadUrl"},
    {command: ".downdouyin" , varname: "douyin", contohUrl:'https://v.douyin.com/ikq8axJ/', lokasi:"result.data.links[0].url"},
    {command: ".downdsnackvideo" , varname: "snackvideo", contohUrl:'https://s.snackvideo.com/p/j9jKr9dR', lokasi: "result.videoUrl"},
    {command: ".downdcocofun" , varname: "cocofun", contohUrl:'https://www.icocofun.com/share/post/379250110809?lang=id&', lokasi:"result.no_watermark"},
    {command: ".downdsoundcloud" , varname: "soundcloud", contohUrl:'https://soundcloud.com/issahalini-official', lokasi:"downloadMp3"},
    {command: ".downdthreads" , varname: "threads", contohUrl:'https://www.threads.net/@cindyyuvia/post/C_Nqx3l', lokasi:"result.video"}
]
export const downImg = [
    {command: ".imgtiktok" , varname: "aio", contohUrl:'https://vt.tiktok.com/ZSudELyTDsdsddssasa/', lokasi: "data.thumbnail"},
    {command: ".imgpintrs" , varname: "pinterest", contohUrl:'https://pin.it/4CVodSq', lokasi: "result.result.image"},
    {command: ".imgig" , varname: "igdl", contohUrl:'https://www.instagram.com/p/ByxKbUSnubS/?eig_web_copy_link', lokasi: "result[0].url"},
]
export const list = [
    ['.listgame', '.game'],
    ['.liststiker', '.stiker'],
    ['.chatanime', '.anime'],
    '.islami', '.img', '.vid',
    '.msk', '.topup', '.pulsa', '.data',
    '.vcr', '.admin', '.viddownload', '.imgdownload'
]

export const cek = [
    '.cekiq', '.cekjodoh', '.cekkodam'
]

export const stiker = [
    '.stikeranim', '.stikerteks', '.stikerjmk',
    '.stikerwowo', '.stikerrandom',
]

export const img = [
    '.imganim', '.imgteks', '.imgjmk',
    '.imgwowo', '.imgrandom', '.imgmeme', '.imgestetik'
]

export const vid = [
    '.videstetik', '.vidjmk', '.vidwowo',
    '.vidrandom', '.vidmeme', '.vidjj'
]

export const topup = [
    { msg: '.tpff', game: 'Free Fire' },
    { msg: '.tpml', game: 'Mobile Legends' },
    { msg: '.tppubg', game: 'PUBG Mobile' },
    { msg: '.tprbx', game: 'Roblox' },
    { msg: '.tpgshin', game: 'Genshin Impact' },
    { msg: '.tplol', game: 'League of Legends' },
    { msg: '.tphnkai', game: 'Honkai Impact' },
    { msg: '.tpvalo', game: 'Valorant' },
    { msg: '.tphok', game: 'Honor of Kings' },
    { msg: '.tpzzz', game: 'Zenless Zone Zero' },
    { msg: '.tpaov', game: 'AOV' },
    { msg: '.tpea', game: 'EA Games' },
    { msg: '.tpafk', game: 'AFK Arena' },
    { msg: '.tpvidio', game: 'Vidio' },
    { msg: '.tpminecraft', game: 'Minecraft' },
    { msg: '.tpspsus', game: 'Super Sus' },
    { msg: '.tpcodm', game: 'Call of Duty Mobile' },
    { msg: '.tpmladv', game: 'Mobile Legends Adventure' },
    { msg: '.tpmcgg', game: 'Magic chess gg' },
    { msg: '.tparenab', game: 'Arena Breakout' },
    { msg: '.tpblodstrk', game: 'Blood Strike' },
    { msg: '.tpdeltaforc', game: 'Delta Force' },
    { msg: '.tpindus', game: 'Indus' },
    { msg: '.tpgglvcr', game: 'Google voucher' },
    { msg: '.tpracingmstr', game: 'Racing master' },
    { msg: '.tpundown', game: 'Undown' },
    { msg: '.tp8ball', game: '8 Ball' },
    { msg: '.tpheavendmn', game: 'Heaven domain' },
    { msg: '.tpdragonhtrs', game: 'Dragon hunters' },
    { msg: '.tpspeeddrft', game: 'speed drift' },
    { msg: '.tpcrisisact', game: 'Crisis acrion' },
    { msg: '.tpzepeto', game: 'Zapeto' },
    { msg: '.tpfootbllmngr', game: 'Foot ball maneger' },
    { msg: '.tpfrostwarr', game: 'Frost warr' },
    { msg: '.tpragnarogclsc', game: 'Ragnarog classic' }
];

export const pulsa = [
    { msg: '.pulstri', puls: 'tri' },
    { msg: '.pulstelkom', puls: 'telkomsel' },
    { msg: '.pulsindost', puls: 'indosat' },
    { msg: '.pulsxl', puls: 'xl' },
    { msg: '.pulsim3', puls: 'im3' },
    { msg: '.pulsaxis', puls: 'axis' },
    { msg: '.pulssmartf', puls: 'smartfren' },
    { msg: '.pulsbyu', puls: 'byu' },
    { msg: '.dattri', puls: 'data tri' },
    { msg: '.dattelkom', puls: 'data telkomsel' },
    { msg: '.datindost', puls: 'data indosat' },
    { msg: '.datxl', puls: 'data xl' },
    { msg: '.datim3', puls: 'data im3' },
    { msg: '.dataxis', puls: 'data axis' },
    { msg: '.datsmartf', puls: 'data smartfren' },
    { msg: '.datbyu', puls: 'data byu' },
];

export const vcr = [
    { msg: '.tknpln', value: 'Token PLN'},
    { msg: '.vcrvidio', value: 'Voucher vidio'},
    { msg: '.vcrggply', value: 'Voucher google play'},
    { msg: '.vcrrbx', value: 'Voucher robux'},
    { msg: '.vcrvision', value: 'Voucher vision'},
    { msg: '.vcrtiktokkoin', value: 'Voucher tiktok koin'},
    { msg: '.vcrminecraft', value: 'Voucher minecraft'},
    { msg: '.vcrtwitch', value: 'Voucher twitch'},
    { msg: '.vcrsteam', value: 'Voucher steam'},
    { msg: '.vcrnitendo', value: 'Voucher nitendo'},
    { msg: '.vcrgarenashll', value: 'Voucher garena shell'},
    { msg: '.vcrxbox', value: 'Voucher xbox'},
]

export const game = [
  { game: '.sudoku', link: 'https://www.crazygames.com/id/game/sudoku-szc' },
  { game: '.ulartangga', link: 'https://www.crazygames.com/id/game/snakes-and-ladders' },
  { game: '.uno', link: 'https://www.crazygames.com/id/game/uno-online' },
  { game: '.poker', link: 'https://www.crazygames.com/id/game/erth-poker' },
  { game: '.tord', link: 'https://truthordare.app/' },
  { game: '.snack', link: 'https://www.crazygames.com/game/worms-zone' },
  { game: '.ludo', link: 'https://www.crazygames.com/id/game/ludo-legend' },
  { game: '.pingpong', link: 'https://www.crazygames.com/id/game/table-tennis-world-tour' },
  { game: '.tictactoe', link: 'https://www.crazygames.com/id/game/tic-tac-toe' },
  { game: '.monopoli', link: 'https://www.crazygames.com/id/game/polybusiness' },
  { game: '.puzzle', link: 'https://www.crazygames.com/id/c/puzzlee' },
  { game: '.darts', link: 'https://www.crazygames.com/game/darts-club' },
  { game: '.tennis', link: 'https://www.crazygames.com/id/game/tennis-masters' },
  { game: '.pool', link: 'https://www.crazygames.com/id/game/8-ball-billiards-classic' },
  { game: '.mathgame', link: 'https://www.crazygames.com/id/game/math-push' },
  { game: '.popit', link: 'https://www.crazygames.com/id/game/pop-it-duel' },
  { game: '.rubix', link: 'https://rubikscu.be/' },
  { game: '.carrom', link: 'https://www.crazygames.com/id/game/disk-strike-carrom-challenge' },
  { game: '.hammerhit', link: 'https://id.y8.com/games/hammer_hit' },
  { game: '.bowling', link: 'https://www.crazygames.com/id/game/classic-bowling' },
  { game: '.checkers', link: 'https://www.crazygames.com/id/game/checkers-free' },
  { game: '.pinball', link: 'https://www.crazygames.com/id/game/pinball-idle' },
  { game: '.minisoccer', link: 'hhttps://www.crazygames.com/id/game/rocketgoal-io' },
  { game: '.mancala', link: 'https://www.crazygames.com/id/game/mancala-classic' },
  { game: '.dotsandboxes', link: 'https://www.coolmathgames.com/0-dots-and-boxes' },
  { game: '.domino', link: 'https://www.crazygames.com/id/game/domino-duel-uit' },
  { game: '.yesorno', link: 'https://www.crazygames.com/game/yes-or-no-challenge' },
  { game: '.pizza', link: 'https://www.crazygames.com/id/game/pizza-challenge' },
  { game: '.glowit', link: 'https://www.crazygames.com/id/game/glowit-two-players' },
  { game: '.fiveo', link: 'https://www.crazygames.com/id/game/five-o' },
  { game: '.lazzergrrl', link: 'https://www.crazygames.com/game/lazergrrl' },
  { game: '.islandroccer', link: 'https://poki.com/id/g/soccer-skills-world-cup' },
  { game: '.donutvsdonut', link: 'https://www.crazygames.com/id/game/donut-vs-donut' },
  { game: '.tuggowar', link: 'https://www.twoplayergames.org/game/tug-war' },
  { game: '.bowman', link: 'https://www.crazygames.com/game/bowman' },
  { game: '.minesweeper', link: 'https://cardgames.io/minesweeper/' },
  { game: '.hexa', link: 'https://www.crazygames.com/game/hexa-sort' },
  { game: '.unpuzzle', link: 'https://www.crazygames.com/game/unpuzzle-tap-away-puzzle-game' },
  { game: '.pipeout', link: 'https://www.crazygames.com/id/game/plumber' },
  { game: '.rollup', link: 'https://www.crazygames.com/id/game/rollup-tiles' },
  { game: '.link', link: 'https://www.crazygames.com/id/game/link' },
  { game: '.beam', link: 'https://www.crazygames.com/id/game/beam' },
  { game: '.emojipuzzle', link: 'https://www.crazygames.com/id/game/emoji-puzzle' },
  { game: '.mahjong', link: 'https://www.crazygames.com/id/game/mahjongg-solitaire' },
  { game: '.nutspuzzle', link: 'https://www.crazygames.com/game/bolts-and-nuts' },
  { game: '.masterofnumber', link: 'https://www.crazygames.com/game/master-of-numbers-qmz' },
  { game: '.yacht', link: 'https://www.crazygames.com/game/yahtzee-online' },
  { game: '.entropy', link: 'https://www.crazygames.com/id/game/entropy' },
  { game: '.get1000', link: 'https://www.crazygames.com/id/game/get-1000' },
  { game: '.pixblock', link: 'https://www.crazygames.com/game/blockbuster-puzzle' },
  { game: '.splotch', link: 'https://www.crazygames.com/id/game/splotch' },
  { game: '.orange', link: 'https://www.crazygames.com/id/game/orange' },
  { game: '.black', link: 'https://www.crazygames.com/id/game/black' },
  { game: '.red', link: 'https://www.crazygames.com/id/game/red' },
  { game: '.nonogram', link: 'https://www.crazygames.com/game/nonogram' },
  { game: '.xor', link: 'https://www.crazygames.com/id/game/xor' },
  { game: '.sokoban', link: 'https://www.crazygames.com/id/game/sokoban' },
  { game: '.redirect', link: 'https://www.crazygames.com/game/redirect-arq' },
  { game: '.ruya', link: 'https://www.crazygames.com/id/game/ruya' },
  { game: '.baseball', link: 'https://www.crazygames.com/id/game/baseball' },
  { game: '.miniputt', link: 'https://www.crazygames.com/id/game/mini-putt' },
  { game: '.boxing', link: 'https://www.crazygames.com/id/game/boxing-random' },
  { game: '.volley', link: 'https://www.crazygames.com/id/game/volley-random' },
  { game: '.punchers', link: 'https://www.crazygames.com/id/game/punchers' },
  { game: '.fourcolors', link: 'https://www.crazygames.com/game/uno-online' },
  { game: '.kuja', link: 'https://www.crazygames.com/id/game/kuja' },
  { game: '.cubicrush', link: 'https://www.crazygames.com/id/game/cubic-rush' },
  { game: '.dodgeball', link: 'https://www.crazygames.com/game/dodgeball' },
  { game: '.gengsters', link: 'https://www.crazygames.com/id/game/gangsters' },
  { game: '.rollingballs', link: 'https://www.crazygames.com/game/crazy-roll-3d' },
  { game: '.whooo?', link: 'https://www.crazygames.com/id/game/whooo' },
  { game: '.bloxorz', link: 'https://www.crazygames.com/id/game/bloxorz' },
  { game: '.rotate', link: 'https://www.crazygames.com/id/game/rotate' },
  { game: '.glitch', link: 'https://www.crazygames.com/id/game/glitch-mkf' },
  { game: '.growmi', link: 'https://www.crazygames.com/id/game/growmi' },
  { game: '.green', link: 'https://www.crazygames.com/id/game/green' },
  { game: '.pollytrack', link: 'https://www.crazygames.com/id/game/polytrack' },
  { game: '.rodha', link: 'https://www.crazygames.com/id/game/rodha' },
  { game: '.mirrorroom', link: 'https://www.crazygames.com/game/mirror-room-escape' },
  { game: '.tilo', link: 'https://www.crazygames.com/id/game/tilo' },
  { game: '.monomove', link: 'https://www.crazygames.com/id/game/mono-move' },
  { game: '.googlefeud', link: 'https://www.crazygames.com/id/game/google-feud' },
  { game: '.jetrush', link: 'https://www.crazygames.com/id/game/jet-rush' },
  { game: '.countmasters', link: 'https://www.crazygames.com/game/count-masters-stickman-games' },
  { game: '.wordguessr', link: 'https://www.crazygames.com/game/word-search-lyg' },
  { game: '.doodleroad', link: 'https://www.crazygames.com/id/game/doodle-road' },
  { game: '.marblerun', link: 'https://www.crazygames.com/id/game/marble-run' },
  { game: '.driftboss', link: 'https://www.crazygames.com/id/game/drift-boss' },
  { game: '.replyrun', link: 'https://www.crazygames.com/id/game/reply-run' },
  { game: '.openhouse', link: 'https://www.crazygames.com/id/game/open-house' },
  { game: '.layersrol', link: 'https://www.crazygames.com/id/game/layers-roll' },
  { game: '.smashkarts', link: 'https://www.crazygames.com/id/game/smash-karts' },
  { game: '.fragen', link: 'https://www.crazygames.com/id/game/fragen' },
  { game: '.sugarrush', link: 'https://www.crazygames.com/id/game/sugar-rush' },
  { game: '.stickman', link: 'http://crazygames.com/id/game/ragdoll-archers' },
  { game: '.skillwarz', link: 'https://www.crazygames.com/id/game/skillwarz' },
  { game: '.gulag', link: 'https://www.crazygames.com/id/game/gulag' },
  { game: '.takeactions', link: 'https://www.crazygames.com/id/game/take-actions' },
  { game: '.furyfoot', link: 'https://www.crazygames.com/game/anger-foot-3d' },
  { game: '.tunnel54', link: 'https://www.crazygames.com/id/game/tunnel-54' },
  { game: '.gunsandmagic', link: 'https://www.crazygames.com/id/game/guns-and-magic' }
];

export const char = [
    '.noa', '.shiroko', '.hoshino', '.yuuka',
    '.hikari', '.furina', '.hutao', '.klee',
    '.miko', '.lumine', '.raiden'
]

export const cari_anim = [
    { msg: '.carigenre', value: 'genres' },
    { msg: '.caritotaleps', value: 'total_eps' },
    { msg: '.carifulleps', value: 'link' },
    { msg: '.carifulltrailer', value: 'trailer' },
    { msg: '.carifulldesc', value: 'description' },
    { msg: '.carifulldurasi', value: 'duration' },
    { msg: '.caritgglrilis', value: 'start_eps' },
    { msg: '.carikarakter', value: 'characters' },
    { msg: '.caribanner', value: 'poster' },
]