async function get_lirik(text) {
    const itunesRes = await fetch(`https://itunes.apple.com/search?term=${encodeURIComponent(text)}&entity=song&limit=1`);
    const itunesData = await itunesRes.json();
    if (itunesData.resultCount > 0) {
        const lagu = itunesData.results[0];
        const artis = lagu.artistName;
        const judul = lagu.trackName;
        const lrcRes = await fetch(`https://lrclib.net/api/get?artist_name=${encodeURIComponent(artis)}&track_name=${encodeURIComponent(judul)}`);
        const lrcData = await lrcRes.json();
        const format =
            `╔══════════════════╗\n` +
            `🎵  *INFORMASI MUSIK* 🎵\n` +
            `╚══════════════════╝\n\n` +
            `📝 *Judul:* ${judul}\n` +
            `👤 *Artis:* ${artis}\n\n` +
            `──────────────────\n` +
            `📑 *LIRIK LAGU*\n` +
            `──────────────────\n\n` +
            `${lrcData.plainLyrics || "_Lirik tidak ditemukan untuk lagu ini._"}\n\n` +
            `──────────────────\n` +
            `©️ _Generated by MusicBot_`;

        return format;
    } else {
        return null;
    }
}

export default async function carilirik({remoteJid, sock, text, msg}) {
    try {
        const isiTeks = text.replace('.carilirik', '').trim();
        if (!isiTeks) return await sock.sendMessage(remoteJid, { text: "Ketik nama lagu, contoh: .carilirik ghost" });
        const format = await get_lirik(isiTeks);
        if (!format) return await sock.sendMessage(remoteJid, { text: 'tidak menemukan lagu yang anda cari' });
        await sock.sendMessage(remoteJid, {
            text: format
        }, { quoted: msg });

    } catch (err) {
        console.error(err);
        await sock.sendMessage(remoteJid, { text: 'Terjadi kesalahan sistem saat mengirim audio.' });
    }
}